### ISSUE TITLE
Is there anyway to compile this from Xcode? I get 'gtk/gtk.h' file not found

### ISSUE THREAD

**Issue by thepost** [TokamakUI/Tokamak#406] opened 2021-05-24 15:01 UTC
I'm thinking that I could add a script to run `carton dev` and `^c` from Xcode so that it launches in the browser straight from Xcode. 

Currently when compiling though I get `'gtk/gtk.h' file not found` in `type_check.h`. Any ideas how to resolve this?

**Comment by MaxDesiatov** [comment] 2021-05-30 21:10
As far as I'm aware, Xcode is not extendable in this way. Even if you had a script integrated as a build phase, the main build process would still require some Apple device set as a target, which most probably won't work cleanly with the build system. If anyone knows of any alternatives, I'm happy to consider those.

**Comment by MaxDesiatov** [comment] 2021-06-03 12:12
Closing this as something caused by Xcode limitations, I don't think it's related to Tokamak. Feel free to reopen if that's incorrect or if there are any alternatives that we could implement on our side.

**Closed by MaxDesiatov** 2021-06-03 12:12 UTC
